# Generated by Django 2.2.1 on 2019-06-03 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodenuncia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denuncia', to=settings.AUTH_USER_MODEL),
        ),
    ]
