# Generated by Django 2.2.2 on 2019-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_denuncia', '0002_auto_20190603_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodenuncia',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
