# Generated by Django 2.2.7 on 2019-12-01 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_denuncia', '0003_auto_20190618_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodenuncia',
            name='data_hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
