# Generated by Django 2.2.7 on 2019-12-01 17:06

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_denuncia', '0004_usuariodenuncia_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodenuncia',
            name='data_hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2019, 12, 1, 17, 6, 43, 396113, tzinfo=utc))]),
        ),
    ]
