# Generated by Django 2.2.1 on 2019-09-30 23:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, validators=[users.models.User.validate_CPF]),
        ),
    ]
