# Generated by Django 2.2.1 on 2019-06-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_denuncia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='tipo_denuncia.TipoDenuncia')),
            ],
        ),
    ]
