# Generated by Django 2.2.1 on 2019-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodenuncia',
            name='icone',
            field=models.CharField(default='exclamation-triangle', max_length=200),
        ),
    ]
