# Generated by Django 2.2.7 on 2019-11-22 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_denuncia', '0003_auto_20190618_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDenunciaImagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('usuario_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denuncia_imagens', to='usuario_denuncia.UsuarioDenuncia')),
            ],
        ),
    ]
