export const GET_DENUNCIAS_USUARIO = "GET_DENUNCIAS_USUARIO";

export const DELETE_DENUNCIA_USUARIO = "DELETE_DENUNCIA_USUARIO";

export const ADD_DENUNCIA_USUARIO = "ADD_DENUNCIA_USUARIO";

export const GET_TIPO_DENUNCIA = "GET_TIPO_DENUNCIA";

export const DELETE_TIPO_DENUNCIA = "DELETE_TIPO_DENUNCIA";

export const ADD_TIPO_DENUNCIA = "ADD_TIPO_DENUNCIA";

export const GET_DENUNCIA = "GET_DENUNCIA";

export const DELETE_DENUNCIA = "DELETE_DENUNCIA";

export const ADD_DENUNCIA = "ADD_DENUNCIA";

export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";

export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";
