# Generated by Django 2.2.1 on 2019-06-03 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
